### ISSUE TITLE
Suggestion: Introduce modifyWithSlug & getWithSlug

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#235]
https://github.com/feathersjs/feathers-mongoose/pull/153#issuecomment-268329889

> You can still save the extra queries by using hooks.

```js
function modifyWithSlug(name) {
  return function(hook) {
    if(hook.id !== null) {
      const idField = hook.service.id;
      const query = {
        $or: [{
            [idField]: hook.id
        }, {
            [name]: hook.id
        }]
      };

      hook.id = null;
      hook.params.query = query;
    }
  }
}

function getWithSlug(name) {
  return function(hook) {
    const idField = hook.service.id;
    const query = {
      $or: [{
          [idField]: hook.id
      }, {
          [name]: hook.id
      }]
    };

    return hook.service.find({
      query,
      paginate: false
    }).then(result => {
      if(result.length === 1) {
        hook.result = result[0];
      }

      return hook;
    });
  }
}
```

> Can be used like

```js
const modify = modifyWithSlug('slug');
const get = getWithSlug('slug');

app.before({
  get,
  patch: modify,
  remove: modify,
  update: modify
});
```

> and won't make any additional queries.

I'd really prefer a generic solution that works across all adapters mainly because I know the pain of maintaining and documenting all the adapters and keeping shared functionality in sync. We should try to only add functionality that can't be accomplished any other way and to me this use case is exactly what hooks are for.

**Comment by evilboss** [comment]
Not working for me using updated feathers plus generator

**Comment by eddyystop** [comment]
The hooks listed above are extracted from the comment mentioned. They are a note for me to consider adding such hooks. I have not tested them.

@evilboss Could you be more specfic please about your results.
