### ISSUE TITLE
Suggestion: Add a permissions/roles hook

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#328]
```js
app.service('myservice').hooks({
  before(context) {
    const { method, path } = context;
    const { user = {} } = context.params;

    if(!user.permissions.includes(`${path}:${method}`)) {
      throw new Error('You are not allowed to access this');
    }
  }
});
```

**Comment by bertho-zero** [comment]
https://github.com/feathersjs-ecosystem/feathers-permissions is forgotten?

**Comment by eddyystop** [comment]
I don't think that handles roles.

**Comment by eddyystop** [comment]
From Slack:
roel [12 hours ago]
This is my hook that checks the MINIMAL permission needed to access a service action:


roel [12 hours ago]
```const errors = require('@feathersjs/errors');

module.exports = role => { // eslint-disable-line no-unused-vars
  return async context => {
    const ROLES = context.app.get('userRoles');
    
    if (!role) throw new errors.NotAuthenticated('Role is required. (hasRole)');
    if (!ROLES.includes(role)) throw new errors.NotAuthenticated('Unrecognized role. (hasRole)');

    if (context.type !== 'before') {
      throw new Error('The \'requiresMinRole\' hook should only be used as a \'before\' hook.');
    }

    // If it was an internal call then skip this hook
    if (!context.params.provider) {
      return context;
    }
    
    // Get the authenticated user
    const user = context.params.user;
    if (!user || !user.role) throw new errors.NotAuthenticated();

    const error = new errors.Forbidden('You do not have valid permissions to access this.');
 
    // Check customer role
    if (role === ROLES[0] && !ROLES.includes(user.role))
      // Employees and admins are also allowed here
      throw error;
    // Check employee role
    if (role === ROLES[1] && user.role === ROLES[0])
      // Admina are also allowed here
      throw error;
    // Check admin role
    if (role === ROLES[2] && user.role !== ROLES[2])
      throw error;
    
    return context;
  };
};
```
(edited)


roel [12 hours ago]
And an isRole hook to check the exact ROLE:


roel [12 hours ago]
```// Use this hook to manipulate incoming or outgoing data.
// For more information on hooks see: http://docs.feathersjs.com/api/hooks.html
const errors = require('@feathersjs/errors');

module.exports = function (role) { // eslint-disable-line no-unused-vars
  return context => {
    const ROLES = context.app.get('userRoles');

    if (!role) throw new errors.NotAuthenticated('Role is required. (hasRole)');
    if (!ROLES.includes(role)) throw new errors.NotAuthenticated('Unrecognized role. (hasRole)');

    // Get the authenticated user
    const user = context.params.user;
    return user && user.role && (role === user.role);
  };
};
```

**Comment by eddyystop** [comment]
https://blog.feathersjs.com/authorization-with-casl-in-feathersjs-app-fd6e24eefbff

**Comment by beeplin** [comment]
in fact `feathers-permissions` can be used for groups/roles: 

https://github.com/feathersjs-ecosystem/feathers-permissions/blob/master/src/hooks/check-permissions.js#L32-L35

Suppose we have an `users` service with the following structure:  

```js
{
  _id: xxx,
  name: xxx,
  roles: ['admin', 'user']
}
```
 
And have the following hook setting:

```js
someService.hooks({
  before: {
    all: [ 
      authenticate('jwt'), 
      checkPermissions({ 
        on: 'user', 
        field: 'roles', 
        roles: [ 'admin', 'superadmin' ] 
      })
    ]
  }
})
```

Then it works.

**Comment by beeplin** [comment]
For simple roles control, both `feathers-permission` and `feathers-authentication-hooks` works well. However hooks in `feathers-authentication-hooks` can only do several given actions after identifying user's roles -- reject, restrict query, etc.

Using `feathers-permission`, we can use `checkPermissions` to identify user's role/group/permission, then use `isPermitted` to reject, or manually use `iff(context => context.params.permitted, someHook()).else(anotherHook())` to customize the following actions.

Of coz in practice I tend to use just `iff` to do such things with customized predicates. This makes the hook chain more readable.

**Comment by eddyystop** [comment]
https://blog.feathersjs.com/access-control-strategies-with-feathersjs-72452268739d

https://blog.feathersjs.com/authorization-with-casl-in-feathersjs-app-fd6e24eefbff

https://github.com/stalniy/casl-feathersjs-example
