### ISSUE TITLE
Suggestion: consider forking a hook to slugify a field

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#342]
https://www.npmjs.com/package/feathers-slugify

https://gist.github.com/roelvan/a241b75d9b25eeafd337c78764bd3ceb
```js
// Can be run as a before and after hook
const { alterItems } = require('feathers-hooks-common');
const slug = require('slug');

module.exports = function (fromField, toField = 'slug') { // eslint-disable-line no-unused-vars
  return alterItems(item => {
    if (!item[fromField])
      throw new Error(`No such field [${fromField}]`);
    item[toField] = slug(item[fromField]);
  });
};
```

**Comment by bravo-kernel** [comment]
I think this would be a very welcome addition to this repo as it was the first thing that stopped my rapid progress through the framework, I totally believed `setSlug()` was meant for this.

BTW, the feathers-slugify hook works fine but could do with a/an optional database lookup to prevent duplicate slugs.
