### ISSUE TITLE
Suggestion: Add DB specific hooks

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#347]
https://github.com/feathersjs/feathers/issues/334

https://www.npmjs.com/package/feathers-mongodb-fuzzy-search

**Comment by eddyystop** [comment]
See also https://github.com/feathers-plus/feathers-hooks-common/issues/248

**Comment by rayfoss** [comment]
I'm also running into issue where querying from a socket.io client won't work as feathers-mongodb and feathers-nedb both save dates and comparisons between dates and ISO strings fail. I'm going the route of converting all my dates to ISO strings or MS UTS.
