### ISSUE TITLE
dedup / debounce calls

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#36]
Idea for a new hook from bede

"Has anyone here had to develop a pattern for ‘debouncing’ (not quite debouncing) requests using feathers-client? e.g. I have two calls to the same find, but only care about the result of one:"
```javascript
app('projects').find(…);
// While request is happening request is made again
app('projects').find(…);
// Should just return promise from first request
```

**Comment by eddyystop** [comment]
https://github.com/feathersjs/feathers-rest/issues/91#issuecomment-263636928

**Comment by ekryski** [comment]
This is likely similar to https://github.com/feathersjs/feathers-batch.

**Comment by eddyystop** [comment]
So feathers-batch de-dups identical calls? Info, thanks.

**Comment by daffl** [comment]
feathers-batch just allows to batch several calls into one.

**Comment by eddyystop** [comment]
This might be useful: https://github.com/jhurliman/node-rate-limiter
