### ISSUE TITLE
setSlug not working in buzzard

### ISSUE THREAD

**Issue by m4n0v31** [feathersjs-ecosystem/feathers-hooks-common#380]
Due to the changes in buzzard, setSlug should take the slugs from context.params.route[slug] instead of context.params[slug]

**Comment by eddyystop** [comment]
Could you submit a PR? Thanks.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs-ecosystem/feathers-hooks-common/commit/3f923136ded2e5a1a5ce23e38cd96253b19b1525
