### ISSUE TITLE
Use with create-react-app

### ISSUE THREAD

**Issue by saiichihashimoto** [feathersjs-ecosystem/feathers-hooks-common#382]
### Steps to reproduce

Using [create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) with this module breaks the build.

I'm using `@feathers/client` rather than `@feathers/feathers` and, when I exclude this module, everything builds. With it, the build breaks.

### Expected behavior
The create-react-app build should not break.

### Actual behavior
It does break. :-P

![image](https://user-images.githubusercontent.com/2819256/39260827-6d9bc350-486f-11e8-89bb-701d119d5a18.png)

It seems to have the same error as using `@feathers/feathers` does, ie something in `@feathersjs/errors`.

Very similar to https://github.com/feathersjs-ecosystem/feathers-localstorage

**Comment by eddyystop** [comment]
You will need to provide information about what causes the issue.

**Comment by saiichihashimoto** [comment]
Sorry, I meant to say it was very similar to https://github.com/feathersjs-ecosystem/feathers-localstorage/issues/66

I'm using create-react-app for a frontend webapp app and it needs it's dependencies to be transpiled to be included properly.

With that other issue @daffl [figured out](https://github.com/feathersjs-ecosystem/feathers-localstorage/issues/66#issuecomment-381268307) that some unbuilt files were making it through. Maybe that's similar.

**Comment by eddyystop** [comment]
I don't use create-react-app. A PR would be welcome.

**Comment by saiichihashimoto** [comment]
It really just boils down to there being no [build step](https://github.com/feathersjs-ecosystem/feathers-localstorage/blob/master/package.json#L31). Is this supposed to be isomorphic?

**Comment by bertho-zero** [comment]
I think this problem can be fixed with this:
https://github.com/final-form/react-final-form/blob/7dacf6392f44c8c31ec57d4b3103637ffd5f0f2d/package.json#L6-L8

**Comment by eddyystop** [comment]
FeathersJS repos all had a build step in Auk. That was removed for server-only packages in Buzzard. The build step was removed from this repo by accident.

I'll fix this next time I address the repo. You can run a webpack step yourself in the meantime.

**Comment by acontreras89** [comment]
CRA does not like you messing with webpack.

hope we get this fixed sooner rather than later :crossed_fingers:

**Comment by eddyystop** [comment]
feathers-hooks-common is upgraded on a periodic basis.

**Comment by manhldgs** [comment]
is there a fix for this?

**Comment by eddyystop** [comment]
"CRA does not like you messing with webpack." I am not aware of any repo which could work either server or clinet side which does not use either Webpack or Rollup to produce the client side. The component repos of @feathersjs/feathers-client do so. So I don't understand your comment.

If you want to use this repo client side, just run it through Webpack or Rollup. Feel free to submit a PR.

**Comment by fratzinger** [comment]
Closing this old issue because no new activity. Please feel free to comment, if the problem still exists with new version `v6.0.0`
