### ISSUE TITLE
keep doesn't keep false values

### ISSUE THREAD

**Issue by cladjules** [feathersjs-ecosystem/feathers-hooks-common#425]
### Steps to reproduce
set the result a value with a boolean set to false
```
hook.result = {
   isABooleam: false,
}
```

call keep:
```
keep('isABoolean')
```

`isABoolean` disappear from the result.

### Expected behavior
`isABoolean` should be returned in the response.

### Actual behavior
`isABoolean` is discarded.

**Comment by eddyystop** [comment]
What version of the feathers hooks are you using?

The tests for the latestversion check that `false` values are retained. https://github.com/feathers-plus/feathers-hooks-common/blob/master/tests/services/keep.test.js#L108-L116
