### ISSUE TITLE
Support $search for MongoDB

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#451]
exports.searchRegex = function () {
  return function (hook) {
    const query = hook.params.query;
    for (let field in query) {
      if(query[field].$search && field.indexOf('$') == -1) {
        query[field] = { $regex: new RegExp(query[field].$search) }
      }
    }
    hook.params.query = query
    return hook
  }
}

**Comment by arfanliaqat** [comment]
this is already possible by [Feathers Mongoose Fuzzy Search](https://github.com/arve0/feathers-mongodb-fuzzy-search)
