### ISSUE TITLE
Clarify fastJoin API docs.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#452]
I've had more than 1 question asking what app and context were in the fastJoin API examples. People seem to jump into fastJoin before properly learning Feathers basics.

We can help them out a bit by adding to the first example `const app = require('./..../src/app')` with a comment about the generator. And mention info about context can be found at https://docs.feathersjs.com/api/hooks.html#hook-context

**Comment by DaddyWarbucks** [comment]
I second this. 

I also think the code examples should be simplified. I think using arrow functions with implicit returns, specifically those that are implicitly returning the result of an expression using `await`, are difficult to parse for people trying to learn fastJoin. fastJoin already feels a bit like magic, so then being introduced to the config in this way seems jarring.

I don't think we should get rid of the arrow functions and async/await, but I do think adding some brackets and returns would help.

I also think that some function parameter re-naming would help in the fastJoin queries, as well as using some `get`s where there are currently `find` with pagination disabled but then selecting `[0]`
