### ISSUE TITLE
Clarification on softDelete2

### ISSUE THREAD

**Issue by germanp** [feathersjs-ecosystem/feathers-hooks-common#455]
Hi,

I'm using feathers with mongoose as a databae adapter. I figured out by testing and reading the code that softDelete2 only works by defining the deletedAt field as a number type instead of as a date like I tried at first time. Maybe it would be a good idea to update the documentation in order to clarify that.

Also, I've found that it uses {deletedAt: { $eq: -1 }}, thats works ok with mongoose, but I don't know if also works well with another connector as $eq doesn't seem to be supported in the common query api (https://docs.feathersjs.com/api/databases/querying.html)

**Comment by eddyystop** [comment]
We decided to use the Linux date to be consistent with createdAt and updatedAt.

Thanks for the $eq comment.
@marshallswain  ^^^

**Comment by marshallswain** [comment]
It’s also compatible with sequelize: https://sequelize.readthedocs.io/en/latest/docs/querying/

**Comment by marshallswain** [comment]
Knex requires a utility: https://github.com/bhoriuchi/knex-doc-filter/blob/master/README.md

**Comment by eddyystop** [comment]
I guess we'll change that to `{ deletedAt: -1 }`

**Comment by aozisik** [comment]
I also had to spend some time trying to figure out why softdelete2 was not working with the mongoose adapter. I agree with @germanp. Would be nice if the documentation mentioned this somehow.

**Comment by eddyystop** [comment]
A PR to the docs would be appreciated. That's how open source is supposed to work.
