### ISSUE TITLE
TypeScript definitions for iff

### ISSUE THREAD

**Issue by deskoh** [feathersjs-ecosystem/feathers-hooks-common#512]
Referencing the type definitions for `iff`.
https://github.com/feathers-plus/feathers-hooks-common/blob/f7a61d39ac487941fca1b09dbf4796641e4d1dee/types/index.d.ts#L560

The `predicate` type should include `boolean` ([Documentation](https://feathers-plus.github.io/v1/feathers-hooks-common/#iff)).

Related source: https://github.com/feathers-plus/feathers-hooks-common/blob/f7a61d39ac487941fca1b09dbf4796641e4d1dee/lib/common/iff-else.js#L17

The same applies to `iffElse` as well.

**Comment by eddyystop** [comment]
Please submit a PR

**Comment by deskoh** [comment]
Submitted PR https://github.com/feathers-plus/feathers-hooks-common/pull/513
