### ISSUE TITLE
TypeScript definition for fastJoin don't reflect examples for recursive resolvers

### ISSUE THREAD

**Issue by homj** [feathersjs-ecosystem/feathers-hooks-common#521]
The types for `RecursiveResolver` don't match the examples from the documentation (and are imo faulty)

### Expected behavior

the `fastJoin` hook allows the specification of recursive resolvers like this:

```typescript
{
    resolver: $select => data => ...
    joins: {
        child: $select => data => ...
   }
}
```

This should also be reflected in the `RecursiveResolver` type for Typescript like this:

```typescript
export interface RecursiveResolver<T> {
    resolver: SimpleResolver<T>;
    joins: {
        [property: string]: SimpleResolver<T> | RecursiveResolver<T>;
    };
}
```

### Actual behavior

The `RecursiveResolver` is defined like this:

```typescript
export interface RecursiveResolver<T> {
    resolver: SimpleResolver<T>;
    joins: ResolverMap<any>;
}
```

Which resolves to:

```typescript
export interface RecursiveResolver<T> {
    resolver: SimpleResolver<T>;
    joins: {
        after?: (context: ResolverContext) => void | Promise<void>;
        before?: (context: ResolverContext) => void | Promise<void>;
        joins: {
            [property: string]: SimpleResolver<T> | RecursiveResolver<T>;
        };
    };
}
```

Here, the types require joins to be nested in another object

### Suggested change

Instead of nesting the `ResolverMap` inside the `RecursiveResolver`, it should extend from it:

```typescript
export interface RecursiveResolver<T> extends ResolverMap<T> {
    resolver: SimpleResolver<T>;
}
```

This only applies if the attributes `after` and `before` can be applied to a `RecursiveResolver` as well (which I'm not entirely sure right now). If that's not the case, the correct type would be:

```typescript
export interface RecursiveResolver<T> {
    resolver: SimpleResolver<T>;
    joins: {
        [property: string]: SimpleResolver<T> | RecursiveResolver<T>;
    }
}
```
### System configuration

**Module versions**:
4.20.7

**Comment by homj** [comment]
@daffl why did you mark this as `won't fix`? could you please elaborate why this is not an issue, or why this won't be fixed?

**Comment by daffl** [comment]
The author of fastJoin is no longer around. A pull request is welcome but current development will be directed towards [@feathersjs/schema](https://github.com/feathersjs/schema) instead.

**Comment by strarsis** [comment]
In case this is useful, you can find `fastJoin` TypeScript examples here in the `feathers-hooks-common` (where `fastJoin` is from) tests:
https://github.com/feathersjs-ecosystem/feathers-hooks-common/blob/c61c8d44b49e7d849f79091c0e3e967c839a91d5/types/tests.ts#L181

Also note that `fastJoin` hook must be used in `after`, not in `before` (yes, I initially misunderstood what and when the hook runs), as otherwise a runtime error occurs at request (e.g. FeathersJS app started with debug logging (`DEBUG=* yarn start`)):
````
@feathersjs/express/rest Error in handler: `Cannot read properties of undefined (reading 'data')` +5ms
[...]
@feathersjs/errors GeneralError(500): Cannot read properties of undefined (reading 'data') +0ms
````
