### ISSUE TITLE
SoftDelete2 throws with feathers-sequelize 5 and above

### ISSUE THREAD

**Issue by TheSinding** [feathersjs-ecosystem/feathers-hooks-common#524]
### Steps to reproduce
- Create a fresh application.
- ~~Update the sequelize package to 6.x~~ Update **feathers-sequelize** to 5 or above
- Add the softdelete2 hook to a service which uses the sequelize adapter.
- Watch the 404, when you delete an item.

Want to look at the code ? 
I've created a test [repo](https://github.com/TheSinding/softDelete2Error).
- Clone it
- Run npm i
- Run npm run test
- The test fails due to the error

### Expected behavior
Should logically delete the item (which it does), and return the item with status code 200.

### Actual behavior
It logically deletes the item, then returns 404 not found

### System configuration

I've narrowed it down to ~~sequelize 6.0~~ **feathers-sequelize**

**Comment by TheSinding** [comment]
Now that i've narrowed it down to feathers-sequelize, should this issue be posted on feathers-sequelize ?

**Comment by RayZoey** [comment]
Hello, do you have a solution?
