### ISSUE TITLE
[FR] simplifyAllObjects

### ISSUE THREAD

**Issue by FossPrime** [feathersjs-ecosystem/feathers-hooks-common#527]
### commonHooks.simplifyAllObjects

An application `create, update, patch` hook that would traverse objects and squash them in your desired manner. By default it would squash mongo ObjectID's, Dates and geoCode objects to strings. With an option we could squash dates to numbers.

This would greatly simplify offline caching of databases, portability, client side performance tuning and client to backend conversion overhead. I don't know about you, but I am tired of having to normalize dates. It would also lay the groundwork for a less picky validateSchema, that would traverse objects for requires, remove them for patch and transform deep string references `schema['a.b.c']` to attributes `schema.a.b.c`

For dates we could start with just ISO8601's, which node does by default with JSON.stringify. Which "2019-08-23T14:03:06.549Z" is in reality just as sortable as 1502303252123, but with more DB overhead. It also postpones the question of whether to use nanoseconds, milliseconds or seconds.

Let me know if this is something you'd like PR'ed

**Comment by rayfoss** [comment]
```
