### ISSUE TITLE
version upgrade for feathers v4

### ISSUE THREAD

**Issue by PowerMogli** [feathersjs-ecosystem/feathers-hooks-common#531]
Do you guys plan to release a version which is compatible with feathers v4?

**Comment by eddyystop** [comment]
What exactly broke from v3 to v4?

**Comment by PowerMogli** [comment]
feathers-hooks-common is using his own feathersjs v3 from internal node_modules. And this version has different code than v4. For example it checks for SKIP in hooks.

**Comment by elaijuh** [comment]
softDelete2 is broken due to `SKIP`
