### ISSUE TITLE
Object spread not supported in legacy Edge

### ISSUE THREAD

**Issue by sechel** [feathersjs-ecosystem/feathers-hooks-common#587]
You use object spread here
https://github.com/feathersjs-ecosystem/feathers-hooks-common/blob/cfd1868bd29f59c852971972a80a986238c557f0/lib/services/stash-before.js#L26
This is bad for a library that can also be used in a client context as it is not supported by Microsoft Edge.

**Comment by daffl** [comment]
Since there is no official client build you will need to set up your transpiler to include this repository and target the JS you need.

**Comment by sechel** [comment]
Ok, no Problem, just wanted to point that out. If you use the Angular standard workflow it's not that easy to include custom transpilers to modify the es2015 target.
