### ISSUE TITLE
Gets bad request when i pass any value with paramsForServer

### ISSUE THREAD

**Issue by GaborTorma** [feathersjs-ecosystem/feathers-hooks-common#590]
e.g.: `clients.find(
				paramsForServer({
					query: {
						_id: '5ec10e63d3e4d3ad2cac4037'
					},
					$fastJoin: {
						campaign: true
					}
				})
I get the following bad request message: _**"Invalid query parameter $client"**_

Missing $client from the @feathersjs adapter-commons filter-query.js/ts.
Working version:
exports.FILTERS = {
    $sort: (value) => convertSort(value),
    $limit: (value, options) => getLimit(parse(value), options.paginate),
    $skip: (value) => parse(value),
    $select: (value) => value,
    **$client: (value) => value**
};

**Comment by fratzinger** [comment]
As stated in the docs, `paramsForServer` should be used with `paramsFromClient`: https://hooks-common.feathersjs.com/hooks.html#paramsfromclient
