### ISSUE TITLE
keep doesn't work as an after hook for get

### ISSUE THREAD

**Issue by nborko** [feathersjs-ecosystem/feathers-hooks-common#640]
I've been using version 4 forever and tried updating to version 5.

In version 5, the keep hook seems to remove all fields when used as an "after" hook of a get service, regardless of the parameters. Downgrading to 4.14.1 seems to work fine.

Example usage:
```js
const hooks = require('feathers-hooks-common')

// setup code deleted

app.service('/siteinfo').hooks({
    before: {
        find: hooks.disallow(),
        create: hooks.disallow(),
        update: hooks.disallow(),
        remove: hooks.disallow()
    },
    after: {
        get: hooks.keep(
            'name',
            'contact',
            'siteUrl'
        )
    }
})
```

Removing the keep hook returns the full record as expected.

I'm wondering if there has been an undocumented API change regarding keep, or am I just using it wrong?

Thanks!

**Comment by daffl** [comment]
It should be backwards compatible so something worth looking at. I'm just wondering why the tests are passing with the prerelease in https://github.com/feathersjs-ecosystem/feathers-hooks-common/pull/623 can you reproduce this in a simple app?

**Comment by nborko** [comment]
With a simple app, no. It works with a basic service, such as:

```js
const feathers = require('@feathersjs/feathers')
const hooks = require('feathers-hooks-common')

const app = feathers()

app.use('/test', {
    async get(id) {
        return {
            id,
            public: 'public data',
            private: 'private data'
        }
    }
})

app.service('/test').hooks({
    before: {
        find: hooks.disallow(),
        create: hooks.disallow(),
        update: hooks.disallow(),
        remove: hooks.disallow()
    },
    after: {
        get: hooks.keep(
            'public'
        )
    }
})

app.service('/test').get(1).then((result) => {
    console.log(result)
})
```

I should have added that my service is created from feathers-mongoose (8.3.3), set up as:
```js
app.use('/siteinfo', service({ Model: organization, id: 'code', lean: false }))
```

where `organization` is a mongoose model, and `code` is a unique index on the collection. So that's harder to set up as a "simple" application without a mongodb backend, and a more complicated use case to diagnose.

**Comment by daffl** [comment]
I'm not sure how this worked for you before, but if you are setting `lean: false` you will get Mongoose models which not be modified by common hooks unless you convert them with `toJSON` first (see the __Important__ section at https://github.com/feathersjs-ecosystem/feathers-mongoose#serviceoptions).

**Comment by nborko** [comment]
Because I have business rules in the backend hooks, I've found it handy to get Mongoose models back from service calls in hooks of other services. I should probably be using Mongoose to make direct DB queries instead of using service calls for that.

I've actually never had any issue with any hook removing fields (like passwords etc.) to this point from the full model.  This particular service never needs to return a model, so problem solved there. Returning an empty object sure does seem like an odd result, though.
