### ISSUE TITLE
batch-loader guide link is broken on the website: https://hooks-common.feathersjs.com

### ISSUE THREAD

**Issue by wz5899** [feathersjs-ecosystem/feathers-hooks-common#648]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Actual behavior
In feathers-common-hook guide, fastjoin section (https://hooks-common.feathersjs.com/guides.html#fastjoin), the batch-loader guide links. The link url (https://hooks-common.feathersjs.com/batch-loader) returns 404. It seems refer to a detail explanation of batch-loader in @feathers-plus/batch-loader but I can't find that anywhere on the website. 

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by fratzinger** [comment]
Docs refer to https://github.com/feathersjs-ecosystem/batch-loader and https://github.com/feathersjs-ecosystem/batch-loader/blob/master/docs/index.md now. Thanks for opening this issue!
