### ISSUE TITLE
alterItems requires returning item when multi is true

### ISSUE THREAD

**Issue by ulucs** [feathersjs-ecosystem/feathers-hooks-common#649]
### Steps to reproduce

I have this hook in `create` in a service with `multi: true`
```
      alterItems((rec) => {
        // auto-approve self
        if (rec.requestor === rec.requestee) {
          rec.approved = true;
        }
      }),
```

### Expected behavior

Item should have `item.approved === true` when created

### Actual behavior

It does not. A working modification is to return `rec` inside the hook function. I will look into this and make a pull request later

**Comment by fratzinger** [comment]
I cannot reproduce this. Please provide reproducible code
