### ISSUE TITLE
IDE (VSCode) confused?

### ISSUE THREAD

**Issue by strarsis** [feathersjs-ecosystem/feathers-hooks-common#656]
### Steps to reproduce
1. Ensure that the `feathers-hooks-common` is installed.
2. Auto-import `alterItems` (VSCode IDE Quick fix ("blue lightbulb"))
3. Note that the FeathersJS app doesn't start: 
`Cannot find module 'feathers-hooks-common/types'`

### Expected behavior
The IDE shouldn't import from `feathers-hooks-common/types` but rather from `feathers-hooks-common`.

### Actual behavior
The IDE imports from `feathers-hooks-common/types`.

### System configuration

**Module versions** Probably this package / metadata.

**NodeJS version**: `v16.14.0`

**Operating System**: `Ubuntu 20.04.4 LTS` on `WSL 2` on Windows 10 `x64`

**Browser Version**: Chrome `98.0.4758.102`

**React Native Version**: (Not used)

**Module Loader**: `vite` (from example FeathersJS project)

**Comment by fratzinger** [comment]
We released a new typescript version of `feathers-hooks-common`. Please try updating `npm i feathers-hooks-common@6` and try the import again. Please let me know if your issue is fixed then.
