### ISSUE TITLE
Link in docs for batch loaders explanation is broken

### ISSUE THREAD

**Issue by L-van-der-merwe** [feathersjs-ecosystem/feathers-hooks-common#657]
Documentation link is broken, please resolve and provide me with the correct link? 

Open this [docs](https://hooks-common.feathersjs.com/batch-loader/guide.html), we get a 404. This link is provided [here](https://hooks-common.feathersjs.com/guides.html#batch-loaders)

**Comment by fratzinger** [comment]
Docs now refer to https://github.com/feathersjs-ecosystem/batch-loader and https://github.com/feathersjs-ecosystem/batch-loader/blob/master/docs/index.md now. Thanks for opening this issue!
