### ISSUE TITLE
iff() hooks are skipped when there's a .else()

### ISSUE THREAD

**Issue by jplespin** [feathersjs-ecosystem/feathers-hooks-common#666]
### Steps to reproduce

Version: 6.1.0 with feathers version 4.5.15

After upgrading from 5.0.6 to 6.1.0, if there's an else, the iff predicate check is skipped and only the else is evaluated. I'm using this in the after hook with something like this:
```
find: [
  iff(isProvider('server'),
    hookA,
  )
  .else(
    iff(hook => hook.path === 'users', hook6, hook7)
  )
]
```
This works fine if it's only iff .

The easiest way I found to reproduce this is to add a missing unit tests in **if-esle.test.ts** and do `npm run test` which fails for that specific use case.
This is the test I added to check:
```
  it('using iff(true, ...).else(...)', () => {
    return iff(true,
      hookFcnSync,
      hookFcnSync,
      hookFcnSync
    )
      .else(
        hookFcnSync
      )(hook)
      // @ts-ignore
      .then((hook: any) => {
        assert.equal(hookFcnSyncCalls, 3);
        assert.equal(hookFcnAsyncCalls, 0);
        assert.equal(hookFcnCalls, 0);

        assert.deepEqual(hook, hookAfter);
      });
  });
```
From what I can tell, I think that this might have been introduced with the 6.0 ts port.
Is this already a known issue? Am I using this wrong?

**Comment by fratzinger** [comment]
Please try again with `v6.1.1` and close this issue if this version fixes your issue :)

**Comment by jplespin** [comment]
Yeah, that fixed it. Thanks a lot!

**Comment by fratzinger** [comment]
Nice. Thanks for your contribution!
