### ISSUE TITLE
Export Error "hrtime" in typescript Vite Application

### ISSUE THREAD

**Issue by martinfruehmorgen** [feathersjs-ecosystem/feathers-hooks-common#676]
Hello,

using
"feathers-hooks-common": "^6.1.2",

with node version 16.15.1 in a vite vue application (typescript) I get the following error:

---
 No matching export in "browser-external:process" for import "hrtime"

    node_modules/feathers-hooks-common/dist/index.mjs:918:9:
      918 │ import { hrtime } from "process";
---

I am using feathers-hooks-common like this:
import { paramsForServer } from 'feathers-hooks-common'

Thanks!
Martin

**Comment by fratzinger** [comment]
Hey Martin 👋,

thanks for the issue. It should be fixed in version `feathers-hooks-common@6.1.3`. Please try and let me know.

**Comment by martinfruehmorgen** [comment]
Hello,

thanks! With 6.1.3 the issue is fixed!

Thanks again,
Martin
