### ISSUE TITLE
Suggestion: `$count` special query param? Where it literally just returns the number in place of `hook.result`.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-hooks-common#81]
What do you guys think about a `$count` special query param? Where it literally just returns the number in place of `hook.result`. The reason I ask is knowing to set `$limit: 0` is a bit esoteric and feels like a hack. Plus with the new populate hook if you wanted to just get a count of the related items you can do

```javascript
function(hook) {
  if(hook.params.query.$count) {
    hook.params.query.$limit = 0;
    delete hook.params.query.$count;
  }
}
```

**Comment by ekryski** [comment]
Agreed. I think this should totally be a thing.

**Comment by hubgit** [comment]
I've been trying to work out how to (for example) add a `commentsCount` property to each `post` object. It seems like this would be a good solution.

**Comment by eddyystop** [comment]
@Alf Eaton, are you asking how to find the number of items satisfying a
query?

For a paginated service you can use
```js
service.find({ query: { ..., $limit: 0 }})
  .then(result => result.total);
```

A non-paginated service would have few enough items for you to read and
count them.

**Comment by hubgit** [comment]
@eddyystop I'm actually trying to get the count of nested objects within a `populate` hook, like this:

```
hooks.populate({
          schema: {
            include: [
              {
                service: 'comments',
                nameAs: 'comments_count',
                parentField: 'id',
                childField: 'post_id',
                query: {
                  $count: true, // this would be nice
                },
              }
            ]
          }
        })
```

**Comment by eddyystop** [comment]
You'd have write your own hook. You could do worse that forking the
legacyPopulate hook if you're joins are just 1 level below the base record.

https://github.com/feathersjs/feathers-hooks-common/blob/master/src/services/legacy-populate.js

**Comment by oussamaABID** [comment]
what about total of find
```js
app.service().find({// query to count})
//count  == result.total 
```
